# Generated by Django 5.1.1 on 2024-09-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rate',
        ),
    ]
